language: node_js
sudo: false

node_js:
  - '4'
  - '6.0'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10.0'
  - '10'
  - '11.0'
  - '11'
  - '12.0'
  - '12'
  - '13.0'
  - '13'
  - 'lts/*'
  - 'node'

before_script:
  - if [ "$TRAVIS_NODE_VERSION" == 4 ]; then
      npm install mocha@5.0.0 eslint@4.19.1 nyc@11.8.0;
    fi

after_script:
  - if [ "$TRAVIS_NODE_VERSION" == 12 ]; then
      npm install --no-save coveralls;
      node_modules/.bin/nyc --reporter=text-lcov node_modules/.bin/mocha |
        node_modules/.bin/coveralls;
    fi

cache:
  directories:
    - node_modules
